// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMPFOBXU34fcy4AUEOgTv1qOAP4o4Aikk',
    appId: '1:728491953584:web:7710ab69e9d9476bed9a75',
    messagingSenderId: '728491953584',
    projectId: 'cassia-bakers-32a93',
    authDomain: 'cassia-bakers-32a93.firebaseapp.com',
    storageBucket: 'cassia-bakers-32a93.firebasestorage.app',
    measurementId: 'G-57V6N2VKZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABgbXTq50EoENruCHOW3txoztzu6F-YLI',
    appId: '1:728491953584:android:147422518d1a3d5fed9a75',
    messagingSenderId: '728491953584',
    projectId: 'cassia-bakers-32a93',
    storageBucket: 'cassia-bakers-32a93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBzUUfAggQEo5qXpmoIir6j_GaF0vbhyk',
    appId: '1:728491953584:ios:f5dabad32302c5c3ed9a75',
    messagingSenderId: '728491953584',
    projectId: 'cassia-bakers-32a93',
    storageBucket: 'cassia-bakers-32a93.firebasestorage.app',
    iosBundleId: 'com.cassiabakery.cassiaBakeryErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBzUUfAggQEo5qXpmoIir6j_GaF0vbhyk',
    appId: '1:728491953584:ios:f5dabad32302c5c3ed9a75',
    messagingSenderId: '728491953584',
    projectId: 'cassia-bakers-32a93',
    storageBucket: 'cassia-bakers-32a93.firebasestorage.app',
    iosBundleId: 'com.cassiabakery.cassiaBakeryErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMPFOBXU34fcy4AUEOgTv1qOAP4o4Aikk',
    appId: '1:728491953584:web:9379ccbc6e15a0c0ed9a75',
    messagingSenderId: '728491953584',
    projectId: 'cassia-bakers-32a93',
    authDomain: 'cassia-bakers-32a93.firebaseapp.com',
    storageBucket: 'cassia-bakers-32a93.firebasestorage.app',
    measurementId: 'G-1F5VLWTTMT',
  );
}
